var moves={
'Absorb':{
type:'Grass',
category:'Special',
pp:25,
power:20,
accuracy:100,
description:'User recovers half of the HP inflicted on opponent.',
act:function(user, target){
	user = {level:20, special_attack:20};
	target = {special_defense:20, type:['Ground']};
	return ((2 * user.level / 5 + 2) * user.special_attack * this.power / target.special_defense / 50 + 2) * types.multiplier(this.type, target.type[0]) * (Math.random()*15+85) / 100;
}
},
'Acid':{
type:'Poison',
category:'Special',
pp:30,
power:40,
accuracy:100,
description:"May lower opponent's Defense or Special Defense one stage.",
probability:10,
},
'Acid Armor':{
type:'Poison',
category:'Status',
pp:40,
description:"Increases user's Defense by two stages.",
},
'Acid Spray':{
type:'Poison',
category:'Special',
pp:20,
power:40,
accuracy:100,
description:"Decreases opponent's Special Defense by two stages.",
probability:100,
},
'Acrobatics':{
type:'Flying',
category:'Physical',
pp:15,
power:55,
accuracy:100,
description:'Stronger when the user does not have a held item.',
},
'Acupressure':{
type:'Normal',
category:'Status',
pp:30,
description:"Randomly raises one of the user's stats by two stages.",
},
'Aerial Ace':{
type:'Flying',
category:'Physical',
pp:20,
power:60,
tm:'TM40',
description:'Cannot miss, regardless of Accuracy or Evasiveness.',
},
'Aeroblast':{
type:'Flying',
category:'Special',
pp:5,
power:100,
accuracy:95,
description:'High Critical-Hit ratio.',
},
'After You':{
type:'Normal',
category:'Status',
pp:15,
description:'Gives target priority in the next turn',
},
'Agility':{
type:'Psychic',
category:'Status',
pp:30,
description:"Raises the user's Speed by two stages.",
},
'Air Cutter':{
type:'Flying',
category:'Special',
pp:25,
power:55,
accuracy:95,
description:'High Critical-Hit ratio.',
},
'Air Slash':{
type:'Flying',
category:'Special',
pp:20,
power:75,
accuracy:95,
description:'May cause flinching.',
probability:30,
},
'Ally Switch':{
type:'Psychic',
category:'Status',
pp:15,
description:'User switches with opposite teammate.',
},
'Amnesia':{
type:'Psychic',
category:'Status',
pp:20,
description:"Raises user's Special Defense by two stages.",
},
'Ancientpower':{
type:'Rock',
category:'Special',
pp:5,
power:60,
accuracy:100,
description:"Might raise all of the user's stats by one stage.",
probability:10,
},
'Aqua Jet':{
type:'Water',
category:'Physical',
pp:20,
power:40,
accuracy:100,
description:'User goes first.',
},
'Aqua Ring':{
type:'Water',
category:'Status',
pp:20,
description:'Restores a little HP each turn.',
},
'Aqua Tail':{
type:'Water',
category:'Physical',
pp:10,
power:90,
accuracy:90,
},
'Arm Thrust':{
type:'Fighting',
category:'Physical',
pp:20,
power:15,
accuracy:100,
description:'Hits 2-5 times in one turn.',
},
'Aromatherapy':{
type:'Grass',
category:'Status',
pp:5,
description:'Cures all status problems in your party.',
},
'Assist':{
type:'Normal',
category:'Status',
pp:20,
description:"In a Double Battle, user randomly attacks with a partner's move.",
},
'Assurance':{
type:'Dark',
category:'Physical',
pp:10,
power:50,
accuracy:100,
description:'Power doubles if opponent already took damage in the same turn.',
},
'Astonish':{
type:'Ghost',
category:'Physical',
pp:15,
power:30,
accuracy:100,
description:'May cause flinching.',
probability:30,
},
'Attack Order':{
type:'Bug',
category:'Physical',
pp:15,
power:90,
accuracy:100,
description:'High Critical-Hit ratio.',
},
'Attract':{
type:'Normal',
category:'Status',
pp:15,
accuracy:100,
tm:'TM45',
description:"If opponent is the opposite gender, it's less likely to attack.",
},
'Aura Sphere':{
type:'Fighting',
category:'Special',
pp:20,
power:90,
description:'Cannot miss, regardless of Accuracy or Evasiveness.',
},
'Aurora Beam':{
type:'Ice',
category:'Special',
pp:20,
power:65,
accuracy:100,
description:"Might lower opponent's Attack.",
probability:10,
},
'Autotomize':{
type:'Steel',
category:'Status',
pp:15,
description:"Decreases user's weight and raises Speed by two stages.",
},
'Avalanche':{
type:'Ice',
category:'Physical',
pp:10,
power:60,
accuracy:100,
tm:'TM72',
description:'Power doubles if user took damage first.',
},
'Barrage':{
type:'Normal',
category:'Physical',
pp:20,
power:15,
accuracy:85,
description:'Hits 2-5 times in one turn.',
},
'Barrier':{
type:'Psychic',
category:'Status',
pp:30,
description:"Raises user's Defense by two stages.",
},
'Baton Pass':{
type:'Normal',
category:'Status',
pp:40,
description:'User switches out and gives stat changes to the incoming Pokemon.',
},
'Beat Up':{
type:'Dark',
category:'Physical',
pp:30,
accuracy:100,
description:'Each Pokemon in your party attacks.',
},
'Belly Drum':{
type:'Normal',
category:'Status',
pp:10,
description:'User loses 50% of its max HP, but Attack raises to maximum.',
},
'Bestow':{
type:'Normal',
category:'Status',
pp:15,
description:"Gives the user's held item to the target.",
},
'Bide':{
type:'Normal',
category:'Physical',
pp:10,
description:'User takes damage for two turns and strikes back double on 3rd.',
},
'Bind':{
type:'Normal',
category:'Physical',
pp:20,
power:15,
accuracy:85,
description:'Damages opponent for 2-5 turns, opponent cannot escape/switch.',
},
'Bite':{
type:'Dark',
category:'Physical',
pp:25,
power:60,
accuracy:100,
description:'May cause flinching.',
probability:30,
},
'Blast Burn':{
type:'Fire',
category:'Special',
pp:5,
power:150,
accuracy:90,
description:'User cannot move next turn.',
},
'Blaze Kick':{
type:'Fire',
category:'Physical',
pp:10,
power:85,
accuracy:90,
description:'High Critical-Hit ratio. May cause a burn.',
probability:10,
},
'Blizzard':{
type:'Ice',
category:'Special',
pp:5,
power:120,
accuracy:70,
tm:'TM14',
description:'May cause freezing.',
probability:10,
},
'Block':{
type:'Normal',
category:'Status',
pp:5,
description:'Opponent cannot flee or switch.',
},
'Blue Flare':{
type:'Fire',
category:'Special',
pp:5,
power:130,
accuracy:85,
description:'May burn the target.',
probability:20,
},
'Body Slam':{
type:'Normal',
category:'Physical',
pp:15,
power:85,
accuracy:100,
description:'May cause paralysis.',
probability:30,
},
'Bolt Strike':{
type:'Electric',
category:'Physical',
pp:5,
power:130,
accuracy:85,
description:'May paralyze the target.',
probability:20,
},
'Bone Club':{
type:'Ground',
category:'Physical',
pp:20,
power:65,
accuracy:85,
description:'May cause flinching.',
probability:10,
},
'Bone Rush':{
type:'Ground',
category:'Physical',
pp:10,
power:25,
accuracy:90,
description:'Hits 2-5 times in one turn.',
},
'Bonemerang':{
type:'Ground',
category:'Physical',
pp:10,
power:50,
accuracy:90,
description:'Hits twice.',
},
'Bounce':{
type:'Flying',
category:'Physical',
pp:5,
power:85,
accuracy:85,
description:'Flies up on the first turn, hits on the 2nd. May cause paralysis.',
probability:30,
},
'Brave Bird':{
type:'Flying',
category:'Physical',
pp:15,
power:120,
accuracy:100,
description:'User receives recoil damage.',
},
'Brick Break':{
type:'Fighting',
category:'Physical',
pp:30,
power:75,
accuracy:100,
tm:'TM31',
description:'Breaks through Reflect and Light Screen barriers.',
},
'Brine':{
type:'Water',
category:'Special',
pp:10,
power:65,
accuracy:100,
tm:'TM55',
description:"Power doubles if opponent's HP is less than 50%.",
},
'Bubble':{
type:'Water',
category:'Special',
pp:30,
power:20,
accuracy:100,
description:"May lower opponent's Speed by one stage.",
probability:10,
},
'Bubblebeam':{
type:'Water',
category:'Special',
pp:20,
power:65,
accuracy:100,
description:"May lower opponent's Speed by one stage.",
probability:10,
},
'Bug Bite':{
type:'Bug',
category:'Physical',
pp:20,
power:60,
accuracy:100,
description:"Receives the effect from the opponent's held berry.",
},
'Bug Buzz':{
type:'Bug',
category:'Special',
pp:10,
power:90,
accuracy:100,
description:"May lower opponent's Special Defense by one stage.",
probability:10,
},
'Bulk Up':{
type:'Fighting',
category:'Status',
pp:20,
tm:'TM08',
description:"Increases user's Attack and Defense by one stage.",
},
'Bulldoze':{
type:'Ground',
category:'Physical',
pp:20,
power:60,
accuracy:100,
description:"May lower the target's Speed by one level.",
probability:100,
},
'Bullet Punch':{
type:'Steel',
category:'Physical',
pp:30,
power:40,
accuracy:100,
description:'User goes first.',
},
'Bullet Seed':{
type:'Grass',
category:'Physical',
pp:30,
power:25,
accuracy:100,
tm:'TM09',
description:'Hits 2-5 times in one turn.',
},
'Calm Mind':{
type:'Psychic',
category:'Status',
pp:20,
tm:'TM04',
description:"Increases user's Special Attack and Special Defense by one stage.",
},
'Camouflage':{
type:'Normal',
category:'Status',
pp:20,
description:"Changes user's type according to the location.",
},
'Captivate':{
type:'Normal',
category:'Status',
pp:20,
accuracy:100,
tm:'TM78',
description:'Foe with opposite gender has its Sp. Attack lowered by 2 stages.',
},
'Charge':{
type:'Electric',
category:'Status',
pp:20,
description:'Power of your Electric-type attacks increase next turn.',
},
'Charge Beam':{
type:'Electric',
category:'Special',
pp:10,
power:50,
accuracy:90,
tm:'TM57',
description:"May raise user's Special Attack.",
probability:70,
},
'Charm':{
type:'Normal',
category:'Status',
pp:20,
accuracy:100,
description:"Lowers opponent's Attack by two stages.",
},
'Chatter':{
type:'Flying',
category:'Special',
pp:20,
power:60,
accuracy:100,
description:'Likely to confuse the opponent.',
probability:50,
},
'Chip Away':{
type:'Normal',
category:'Physical',
pp:20,
power:70,
accuracy:100,
description:"Ignores the target's stat changes.",
},
'Circle Throw':{
type:'Fighting',
category:'Physical',
pp:10,
power:60,
accuracy:90,
description:'In battles, the opponent switches. In the wild, the Pokemon runs.',
},
'Clamp':{
type:'Water',
category:'Physical',
pp:10,
power:35,
accuracy:75,
description:'Damages opponent for 2-5 turns, opponent cannot escape/switch.',
},
'Clear Smog':{
type:'Poison',
category:'Special',
pp:15,
power:50,
description:"Removes all of the target's stat changes.",
},
'Close Combat':{
type:'Fighting',
category:'Physical',
pp:5,
power:120,
accuracy:100,
description:"Decreases user's Defense and Special Defense by one stage.",
},
'Coil':{
type:'Poison',
category:'Status',
pp:20,
description:"Raises the user's Attack, Defense and Accuracy.",
},
'Comet Punch':{
type:'Normal',
category:'Physical',
pp:15,
power:18,
accuracy:85,
description:'Hits 2-5 times in one turn.',
},
'Confuse Ray':{
type:'Ghost',
category:'Status',
pp:10,
accuracy:100,
description:'Confuses opponent.',
},
'Confusion':{
type:'Psychic',
category:'Special',
pp:25,
power:50,
accuracy:100,
description:'May confuse opponent.',
probability:10,
},
'Constrict':{
type:'Normal',
category:'Physical',
pp:35,
power:10,
accuracy:100,
description:"May lower opponent's Speed by one stage.",
probability:10,
},
'Conversion':{
type:'Normal',
category:'Status',
pp:30,
description:"Changes user's type to a type of one of its own moves.",
},
'Conversion 2':{
type:'Normal',
category:'Status',
pp:30,
description:"User changes type to become resistant to opponent's last move.",
},
'Copycat':{
type:'Normal',
category:'Status',
pp:20,
description:"Copies opponent's last move.",
},
'Cosmic Power':{
type:'Psychic',
category:'Status',
pp:20,
description:"Increase user's Defense and Special Defense by one stage.",
},
'Cotton Guard':{
type:'Grass',
category:'Status',
pp:10,
description:"Raises the user's Defense by three stages.",
},
'Cotton Spore':{
type:'Grass',
category:'Status',
pp:40,
accuracy:100,
description:"Sharply reduces opponent's Speed.",
},
'Counter':{
type:'Fighting',
category:'Physical',
pp:20,
accuracy:100,
description:'When hit by a Physical Attack, user strikes back with 2x power.',
},
'Covet':{
type:'Normal',
category:'Physical',
pp:40,
power:60,
accuracy:100,
description:"Opponent's item is stolen by the user.",
},
'Crabhammer':{
type:'Water',
category:'Physical',
pp:10,
power:90,
accuracy:90,
description:'High Critical-Hit ratio.',
},
'Cross Chop':{
type:'Fighting',
category:'Physical',
pp:5,
power:100,
accuracy:80,
description:'High Critical-Hit ratio.',
},
'Cross Poison':{
type:'Poison',
category:'Physical',
pp:20,
power:70,
accuracy:100,
description:'Likely to land a Critical Hit, may poison opponent.',
probability:10,
},
'Crunch':{
type:'Dark',
category:'Physical',
pp:15,
power:80,
accuracy:100,
description:"May decrease opponent's Defense by one stage.",
probability:20,
},
'Crush Claw':{
type:'Normal',
category:'Physical',
pp:10,
power:75,
accuracy:95,
description:"May decrease opponent's Defense by one stage.",
probability:50,
},
'Crush Grip':{
type:'Normal',
category:'Physical',
pp:5,
accuracy:100,
description:'More powerful when opponent has higher HP.',
},
'Curse':{
type:'Ghost',
category:'Status',
pp:10,
description:"Ghosts - Lose 50% of max HP, opponent loses 25% of max HP at the end of each turn. Non-Ghosts - Raises user's Attack and Defense one stage each, but lowers Speed by one stage.",
},
'Cut':{
type:'Normal',
category:'Physical',
pp:30,
power:50,
accuracy:95,
tm:'HM01',
},
'Dark Pulse':{
type:'Dark',
category:'Special',
pp:15,
power:80,
accuracy:100,
tm:'TM79',
description:'May cause flinching.',
probability:20,
},
'Dark Void':{
type:'Dark',
category:'Status',
pp:10,
accuracy:80,
description:'Puts all Pokemon on the field to sleep.',
},
'Defend Order':{
type:'Bug',
category:'Status',
pp:10,
description:"Increases user's Defense and Special Defense by one stage each.",
},
'Defense Curl':{
type:'Normal',
category:'Status',
pp:40,
description:"Increases user's Defense by one stage. Rollout is now stronger.",
},
'Defog':{
type:'Flying',
category:'Status',
pp:15,
description:"Lowers opponent's Evasiveness by one stage.",
},
'Destiny Bond':{
type:'Ghost',
category:'Status',
pp:5,
description:'If the user faints, the opponent also faints.',
},
'Detect':{
type:'Fighting',
category:'Status',
pp:5,
description:"Opponent's attack doesn't affect you, but may fail if used often.",
},
'Dig':{
type:'Ground',
category:'Physical',
pp:10,
power:80,
accuracy:100,
tm:'TM28',
description:'Digs down first turn, attacks in the 2nd. Acts like an Escape Rope on the field.',
},
'Disable':{
type:'Normal',
category:'Status',
pp:20,
accuracy:100,
description:"Opponent can't use its last attack for a few turns.",
},
'Discharge':{
type:'Electric',
category:'Special',
pp:15,
power:80,
accuracy:100,
description:'May cause paralysis.',
probability:30,
},
'Dive':{
type:'Water',
category:'Physical',
pp:10,
power:80,
accuracy:100,
description:'Dives down for the first turn, attacks on the second turn.',
},
'Dizzy Punch':{
type:'Normal',
category:'Physical',
pp:10,
power:70,
accuracy:100,
description:'May cause confusion.',
probability:20,
},
'Doom Desire':{
type:'Steel',
category:'Special',
pp:5,
power:140,
accuracy:100,
description:'Damage occurs 2 turns later.',
},
'Double Hit':{
type:'Normal',
category:'Physical',
pp:10,
power:35,
accuracy:90,
description:'Hits twice.',
},
'Double Kick':{
type:'Fighting',
category:'Physical',
pp:30,
power:30,
accuracy:100,
description:'Hits twice.',
},
'Double Team':{
type:'Normal',
category:'Status',
pp:15,
tm:'TM32',
description:"Increases user's Evasiveness by one stage.",
},
'Double-Edge':{
type:'Normal',
category:'Physical',
pp:15,
power:120,
accuracy:100,
description:'User receives recoil damage equal to 1/8th the damage inflicted.',
},
'Doubleslap':{
type:'Normal',
category:'Physical',
pp:10,
power:15,
accuracy:85,
description:'Hits 2-5 times in one turn.',
},
'Draco Meteor':{
type:'Dragon',
category:'Special',
pp:5,
power:140,
accuracy:90,
description:"Decreases user's Special Attack by 2 stages.",
},
'Dragon Claw':{
type:'Dragon',
category:'Physical',
pp:15,
power:80,
accuracy:100,
tm:'TM02',
},
'Dragon Dance':{
type:'Dragon',
category:'Status',
pp:20,
description:"Increases user's Attack and Speed by one stage each.",
},
'Dragon Pulse':{
type:'Dragon',
category:'Special',
pp:10,
power:90,
accuracy:100,
tm:'TM59',
},
'Dragon Rage':{
type:'Dragon',
category:'Special',
pp:10,
accuracy:100,
description:'Always inflicts 40 HP.',
},
'Dragon Rush':{
type:'Dragon',
category:'Physical',
pp:10,
power:100,
accuracy:75,
description:'May cause flinching.',
probability:20,
},
'Dragon Tail':{
type:'Dragon',
category:'Physical',
pp:10,
power:60,
accuracy:90,
description:'In battles, the opponent switches. In the wild, the Pokemon runs.',
},
'Dragonbreath':{
type:'Dragon',
category:'Special',
pp:20,
power:60,
accuracy:100,
description:'May cause paralysis.',
},
'Drain Punch':{
type:'Fighting',
category:'Physical',
pp:10,
power:75,
accuracy:100,
tm:'TM60',
description:'User recovers half of the damage inflicted on opponent.',
},
'Dream Eater':{
type:'Psychic',
category:'Special',
pp:15,
power:100,
accuracy:100,
tm:'TM85',
description:'Can only be used on a sleeping target. User recovers half of the damage inflicted on opponent.',
},
'Drill Peck':{
type:'Flying',
category:'Physical',
pp:20,
power:80,
accuracy:100,
},
'Drill Run':{
type:'Ground',
category:'Physical',
pp:10,
power:80,
accuracy:95,
description:'High Critical-Hit ratio.',
},
'Dual Chop':{
type:'Dragon',
category:'Physical',
pp:15,
power:40,
accuracy:90,
description:'Hits twice in one turn.',
},
'Dynamicpunch':{
type:'Fighting',
category:'Physical',
pp:5,
power:100,
accuracy:50,
description:'Causes confusion, if it hits.',
probability:100,
},
'Earth Power':{
type:'Ground',
category:'Special',
pp:10,
power:90,
accuracy:100,
description:"May decrease opponent's Special Defense by on stage.",
probability:10,
},
'Earthquake':{
type:'Ground',
category:'Physical',
pp:10,
power:100,
accuracy:100,
tm:'TM26',
description:'Power is doubled if opponent is underground from using Dig.',
},
'Echoed Voice':{
type:'Normal',
category:'Special',
pp:15,
power:40,
accuracy:100,
description:'Power increases each turn if multiple Pokemon in the team also use it.',
},
'Egg Bomb':{
type:'Normal',
category:'Physical',
pp:10,
power:100,
accuracy:75,
},
'Electro Ball':{
type:'Electric',
category:'Special',
pp:10,
accuracy:100,
description:'The faster the user, the stronger the attack.',
},
'Electroweb':{
type:'Electric',
category:'Special',
pp:15,
power:55,
accuracy:95,
description:"Lowers the target's Speed by one level.",
probability:100,
},
'Embargo':{
type:'Dark',
category:'Status',
pp:15,
accuracy:100,
tm:'TM63',
description:'Opponent cannot use hold items.',
},
'Ember':{
type:'Fire',
category:'Special',
pp:25,
power:40,
accuracy:100,
description:'May cause a burn.',
probability:10,
},
'Encore':{
type:'Normal',
category:'Status',
pp:5,
accuracy:100,
description:'Forces opponent to keep using its last more for 2-6 turns.',
},
'Endeavor':{
type:'Normal',
category:'Physical',
pp:5,
accuracy:100,
description:"Reduces opponent's HP to same as user's.",
},
'Endure':{
type:'Normal',
category:'Status',
pp:10,
tm:'TM58',
description:'Always left with at least 1 HP, but may fail if used in a row.',
},
'Energy Ball':{
type:'Grass',
category:'Special',
pp:10,
power:80,
accuracy:100,
tm:'TM53',
description:"May decrease opponent's Special Defense by one stage.",
},
'Entrainment':{
type:'Normal',
category:'Status',
pp:15,
accuracy:100,
description:"Makes target's ability same as user's.",
},
'Eruption':{
type:'Fire',
category:'Special',
pp:5,
power:150,
accuracy:100,
description:"Stronger when the user's HP is higher.",
},
'Explosion':{
type:'Normal',
category:'Physical',
pp:5,
power:250,
accuracy:100,
tm:'TM64',
description:'User faints.',
},
'Extrasensory':{
type:'Psychic',
category:'Special',
pp:30,
power:80,
accuracy:100,
description:'May cause flinching.',
probability:10,
},
'Extremespeed':{
type:'Normal',
category:'Physical',
pp:5,
power:80,
accuracy:100,
description:'User attacks first.',
},
'Facade':{
type:'Normal',
category:'Physical',
pp:20,
power:70,
accuracy:100,
tm:'TM42',
description:'Stronger if user is Burned, Poisoned, or Paralyzed.',
},
'Faint Attack':{
type:'Dark',
category:'Physical',
pp:20,
power:60,
description:'Cannot miss, regardless of Accuracy or Evasiveness.',
},
'Fake Out':{
type:'Normal',
category:'Physical',
pp:10,
power:40,
accuracy:100,
description:'Can only be used in first turn. User goes first, foe flinches.',
probability:100,
},
'Fake Tears':{
type:'Dark',
category:'Status',
pp:20,
accuracy:100,
description:"Decreases opponent's Special Defense by two stages.",
},
'False Swipe':{
type:'Normal',
category:'Physical',
pp:40,
power:40,
accuracy:100,
tm:'TM54',
description:'Always leaves opponent with at least 1 HP.',
},
'Featherdance':{
type:'Flying',
category:'Status',
pp:15,
accuracy:100,
description:"Decreases opponent't Attack by two stages.",
},
'Feint':{
type:'Normal',
category:'Physical',
pp:10,
power:30,
accuracy:100,
description:'Only hits if opponent uses Protect or Detect in the same turn.',
},
'Fiery Dance':{
type:'Fire',
category:'Special',
pp:10,
power:80,
accuracy:100,
description:"May raise the user's Special Attack by one level.",
probability:50,
},
'Final Gambit':{
type:'Fighting',
category:'Special',
pp:5,
accuracy:100,
description:"Inflicts damage equal to the user's remaining HP. User faints.",
},
'Fire Blast':{
type:'Fire',
category:'Special',
pp:5,
power:120,
accuracy:85,
tm:'TM38',
description:'May cause a burn.',
probability:10,
},
'Fire Fang':{
type:'Fire',
category:'Physical',
pp:15,
power:65,
accuracy:95,
description:'May cause a burn or flinching.',
probability:10,
},
'Fire Pledge':{
type:'Fire',
category:'Special',
pp:10,
power:50,
accuracy:100,
description:'Added effects appear if preceded by Grass Pledge or succeeded by Water Pledge.',
},
'Fire Punch':{
type:'Fire',
category:'Physical',
pp:15,
power:75,
accuracy:100,
description:'May cause a burn.',
probability:10,
},
'Fire Spin':{
type:'Fire',
category:'Special',
pp:15,
power:35,
accuracy:85,
description:'Damages opponent for 2-5 turns, opponent cannot escape/switch.',
},
'Fissure':{
type:'Ground',
category:'Physical',
pp:5,
accuracy:30,
description:'An instant 1-hit KO, if it hits.',
},
'Flail':{
type:'Normal',
category:'Physical',
pp:15,
accuracy:100,
description:"The lower the user's HP, the higher the power.",
},
'Flame Burst':{
type:'Fire',
category:'Special',
pp:15,
power:70,
accuracy:100,
description:'May also injure nearby Pokemon.',
},
'Flame Charge':{
type:'Fire',
category:'Physical',
pp:20,
power:50,
accuracy:100,
description:"Inflicts damage and raises the user's Speed by one stage.",
probability:100,
},
'Flame Wheel':{
type:'Fire',
category:'Physical',
pp:25,
power:60,
accuracy:100,
description:'May cause a burn.',
probability:10,
},
'Flamethrower':{
type:'Fire',
category:'Special',
pp:15,
power:95,
accuracy:100,
tm:'TM35',
description:'May cause a burn.',
probability:10,
},
'Flare Blitz':{
type:'Fire',
category:'Physical',
pp:15,
power:120,
accuracy:100,
description:'User receives recoil damage.',
},
'Flash':{
type:'Normal',
category:'Status',
pp:20,
accuracy:100,
tm:'TM70',
description:"Decreases opponent's Accuracy by one stage.",
},
'Flash Cannon':{
type:'Steel',
category:'Special',
pp:10,
power:80,
accuracy:100,
tm:'TM91',
description:"May decrease opponent's Sp. Attack or Sp. Defense by one stage.",
probability:10,
},
'Flatter':{
type:'Dark',
category:'Status',
pp:15,
accuracy:100,
description:'Confuses opponent, but raises its Special Attack by two stages.',
},
'Fling':{
type:'Dark',
category:'Physical',
pp:10,
accuracy:100,
tm:'TM56',
description:'Power depends on held item.',
},
'Fly':{
type:'Flying',
category:'Physical',
pp:15,
power:90,
accuracy:95,
tm:'HM02',
description:'Flies up on the first turn, attacks on the second turn.',
},
'Focus Blast':{
type:'Fighting',
category:'Special',
pp:5,
power:120,
accuracy:70,
tm:'TM52',
description:"May decrease opponent's Special Defense by one stage.",
probability:10,
},
'Focus Energy':{
type:'Normal',
category:'Status',
pp:30,
description:'Increases Critical-Hit ratio by one stage',
},
'Focus Punch':{
type:'Fighting',
category:'Physical',
pp:20,
power:150,
accuracy:100,
tm:'TM01',
description:'Pokemon waits on the first turn, attacks on the second. If the Pokemon is hit between this, the Pokemon flinches instead of attacking.',
},
'Follow Me':{
type:'Normal',
category:'Status',
pp:20,
description:'In Double Battle, the user takes all the attacks.',
},
'Force Palm':{
type:'Fighting',
category:'Physical',
pp:10,
power:60,
accuracy:100,
description:'May cause paralysis.',
probability:30,
},
'Foresight':{
type:'Normal',
category:'Status',
pp:40,
description:"Resets opponent's Evasiveness, Normal-type and Fighting-type attacks can now hit Ghosts, and Ghost-type attacks hit Normal.",
},
'Foul Play':{
type:'Dark',
category:'Physical',
pp:15,
power:95,
accuracy:100,
description:"Uses the opponent's Attack stat.",
},
'Freeze Shock':{
type:'Ice',
category:'Physical',
pp:5,
power:140,
accuracy:90,
description:'Charges for a turn before attacking. May paralyze the target.',
probability:30,
},
'Frenzy Plant':{
type:'Grass',
category:'Special',
pp:5,
power:150,
accuracy:90,
description:'User cannot move in the following turn.',
},
'Frost Breath':{
type:'Ice',
category:'Special',
pp:10,
power:40,
accuracy:90,
description:'Always results in a critical hit.',
probability:100,
},
'Frustration':{
type:'Normal',
category:'Physical',
pp:20,
accuracy:100,
tm:'TM21',
description:'Power raises with the more the user dislikes its trainer.',
},
'Fury Attack':{
type:'Normal',
category:'Physical',
pp:20,
power:15,
accuracy:85,
description:'Hits 2-5 times in one turn.',
},
'Fury Cutter':{
type:'Bug',
category:'Physical',
pp:20,
power:20,
accuracy:95,
description:'Power increases with each consecutive hit.',
},
'Fury Swipes':{
type:'Normal',
category:'Physical',
pp:15,
power:18,
accuracy:80,
description:'Hits 2-5 times in one turn.',
},
'Fusion Bolt':{
type:'Electric',
category:'Physical',
pp:5,
power:100,
accuracy:100,
description:'Power increases if Fusion Flare is used in the same turn.',
},
'Fusion Flare':{
type:'Fire',
category:'Special',
pp:5,
power:100,
accuracy:100,
description:'Power increases if Fusion Bolt is used in the same turn.',
},
'Future Sight':{
type:'Psychic',
category:'Special',
pp:10,
power:100,
accuracy:100,
description:'Damage occurs 2 turns later.',
},
'Gastro Acid':{
type:'Poison',
category:'Status',
pp:10,
accuracy:100,
description:"Cancels out the effect of the opponent's Ability.",
},
'Gear Grind':{
type:'Steel',
category:'Physical',
pp:15,
power:50,
accuracy:85,
description:'Hits twice in one turn.',
},
'Giga Drain':{
type:'Grass',
category:'Special',
pp:10,
power:75,
accuracy:100,
tm:'TM19',
description:'User recovers 50% of the damage inflicted on the opponent.',
},
'Giga Impact':{
type:'Normal',
category:'Physical',
pp:5,
power:150,
accuracy:90,
tm:'TM68',
description:'User cannot move in the following turn.',
},
'Glaciate':{
type:'Ice',
category:'Special',
pp:10,
power:65,
accuracy:95,
description:"Lowers the target's Speed.",
probability:100,
},
'Glare':{
type:'Normal',
category:'Status',
pp:30,
accuracy:90,
description:'Causes paralysis, if it hits.',
},
'Grass Knot':{
type:'Grass',
category:'Special',
pp:20,
accuracy:100,
tm:'TM86',
description:'The heavier the opponent, the stronger the attack.',
},
'Grass Pledge':{
type:'Grass',
category:'Special',
pp:10,
power:50,
accuracy:100,
description:'Added effects appear if preceded by Water Pledge or succeeded by Fire Pledge.',
},
'Grasswhistle':{
type:'Grass',
category:'Status',
pp:15,
accuracy:55,
description:'Puts opponent to sleep, if it hits.',
},
'Gravity':{
type:'Psychic',
category:'Status',
pp:5,
description:'Prevents moves like Fly and Bounce and the Ability Levitate for 5 turns.',
},
'Growl':{
type:'Normal',
category:'Status',
pp:40,
accuracy:100,
description:"Decreases opponent's Attack by one stage.",
},
'Growth':{
type:'Normal',
category:'Status',
pp:40,
description:"Increases user's Attack and Special Attack.",
},
'Grudge':{
type:'Ghost',
category:'Status',
pp:5,
description:"If the users faints after using this move, the PP for the opponent's last move is depleted.",
},
'Guard Split':{
type:'Psychic',
category:'Status',
pp:10,
description:'Averages Defense and Special Defense with the target.',
},
'Guard Swap':{
type:'Psychic',
category:'Status',
pp:10,
description:'User and opponent swap Defense and Special Defense.',
},
'Guillotine':{
type:'Normal',
category:'Physical',
pp:5,
accuracy:30,
description:'An instant 1-hit KO, if it hits.',
},
'Gunk Shot':{
type:'Poison',
category:'Physical',
pp:5,
power:120,
accuracy:70,
description:'May cause poison.',
},
'Gust':{
type:'Flying',
category:'Special',
pp:35,
power:40,
accuracy:100,
},
'Gyro Ball':{
type:'Steel',
category:'Physical',
pp:5,
accuracy:100,
tm:'TM74',
description:'The slower the opponent, the stronger the attack.',
},
'Hail':{
type:'Ice',
category:'Status',
pp:10,
tm:'TM07',
description:'Non-Ice types are damaged for 5 turns.',
},
'Hammer Arm':{
type:'Fighting',
category:'Physical',
pp:10,
power:100,
accuracy:90,
description:"Decreases the user's Speed by one stage.",
},
'Harden':{
type:'Normal',
category:'Status',
pp:30,
description:"Increases the user's Defense by one stage.",
},
'Haze':{
type:'Ice',
category:'Status',
pp:30,
description:'Resets all stat changes.',
},
'Head Charge':{
type:'Normal',
category:'Physical',
pp:15,
power:120,
accuracy:100,
description:'User receives 1/4 the damage it inflicts in recoil.',
},
'Head Smash':{
type:'Rock',
category:'Physical',
pp:5,
power:150,
accuracy:80,
description:'User receives recoil damage.',
},
'Headbutt':{
type:'Normal',
category:'Physical',
pp:15,
power:70,
accuracy:100,
description:'May cause flinching.',
probability:30,
},
'Heal Bell':{
type:'Normal',
category:'Status',
pp:5,
description:"Heals the user's party's status conditions.",
},
'Heal Block':{
type:'Psychic',
category:'Status',
pp:15,
description:'Prevents the opponent from restoring HP for 5 turns.',
},
'Heal Order':{
type:'Bug',
category:'Status',
pp:10,
description:"Recovers half of the user's max HP.",
},
'Heal Pulse':{
type:'Psychic',
category:'Status',
pp:10,
description:"Restores half the target's max HP.",
},
'Healing Wish':{
type:'Psychic',
category:'Status',
pp:10,
description:'The user faints and the next Pokemon released is fully healed.',
},
'Heart Stamp':{
type:'Psychic',
category:'Physical',
pp:25,
power:60,
accuracy:100,
description:'May make the target flinch.',
probability:30,
},
'Heart Swap':{
type:'Psychic',
category:'Status',
pp:10,
description:'Stat changes are swapped with the opponent.',
},
'Heat Crash':{
type:'Fire',
category:'Physical',
pp:10,
accuracy:100,
description:'The heavier the user, the stronger the attack.',
},
'Heat Wave':{
type:'Fire',
category:'Special',
pp:10,
power:100,
accuracy:90,
description:'May cause a burn.',
probability:10,
},
'Heavy Slam':{
type:'Steel',
category:'Physical',
pp:10,
accuracy:100,
description:'The heavier the user, the stronger the attack.',
},
'Helping Hand':{
type:'Normal',
category:'Status',
pp:20,
description:"In Double Battles, boosts the power of the partner's move.",
},
'Hex':{
type:'Ghost',
category:'Special',
pp:10,
power:50,
accuracy:100,
description:'Inflicts more damage if the target has a status condition.',
},
'Hi Jump Kick':{
type:'Fighting',
category:'Physical',
pp:10,
power:130,
accuracy:90,
description:'If it misses, the user loses half their HP.',
},
'Hidden Power':{
type:'Normal',
category:'Special',
pp:15,
accuracy:100,
tm:'TM10',
description:"Type and power depends on user's IV's.",
},
'Hone Claws':{
type:'Dark',
category:'Status',
pp:15,
description:'Raises Attack and Accuracy.',
},
'Horn Attack':{
type:'Normal',
category:'Physical',
pp:25,
power:65,
accuracy:100,
},
'Horn Drill':{
type:'Normal',
category:'Physical',
pp:5,
accuracy:30,
description:'An instant 1-hit KO, if it hits.',
},
'Horn Leech':{
type:'Grass',
category:'Physical',
pp:10,
power:75,
accuracy:100,
description:'Heals the user by half the damage inflicted.',
},
'Howl':{
type:'Normal',
category:'Status',
pp:40,
description:"Increases the user's Attack by one stage.",
},
'Hurricane':{
type:'Flying',
category:'Special',
pp:10,
power:120,
accuracy:70,
description:'May confuse the target.',
probability:30,
},
'Hydro Cannon':{
type:'Water',
category:'Special',
pp:5,
power:150,
accuracy:90,
description:'User cannot move in the following turn.',
},
'Hydro Pump':{
type:'Water',
category:'Special',
pp:5,
power:120,
accuracy:80,
},
'Hyper Beam':{
type:'Normal',
category:'Special',
pp:5,
power:150,
accuracy:90,
tm:'TM15',
description:'User cannot move on the following turn.',
},
'Hyper Fang':{
type:'Normal',
category:'Physical',
pp:15,
power:80,
accuracy:90,
description:'May cause flinching.',
probability:10,
},
'Hyper Voice':{
type:'Normal',
category:'Special',
pp:10,
power:90,
accuracy:100,
},
'Hypnosis':{
type:'Psychic',
category:'Status',
pp:20,
accuracy:60,
description:'Put opponent to sleep, if it hits.',
},
'Ice Ball':{
type:'Ice',
category:'Physical',
pp:20,
power:30,
accuracy:90,
description:'An attack lasting for 5 turns that grows in power.',
},
'Ice Beam':{
type:'Ice',
category:'Special',
pp:10,
power:95,
accuracy:100,
tm:'TM13',
description:'May cause freezing.',
probability:10,
},
'Ice Burn':{
type:'Ice',
category:'Special',
pp:5,
power:140,
accuracy:90,
description:'Charges for a turn before attacking. May burn the target.',
probability:30,
},
'Ice Fang':{
type:'Ice',
category:'Physical',
pp:15,
power:65,
accuracy:95,
description:'May cause freezing and flinching.',
probability:10,
},
'Ice Punch':{
type:'Ice',
category:'Physical',
pp:15,
power:75,
accuracy:100,
description:'May cause freezing.',
probability:10,
},
'Ice Shard':{
type:'Ice',
category:'Physical',
pp:30,
power:40,
accuracy:100,
description:'User attacks first.',
},
'Icicle Crash':{
type:'Ice',
category:'Physical',
pp:10,
power:85,
accuracy:90,
description:'May make the target flinch.',
probability:30,
},
'Icicle Spear':{
type:'Ice',
category:'Physical',
pp:30,
power:25,
accuracy:100,
description:'Hits 2-5 times in one turn.',
},
'Icy Wind':{
type:'Ice',
category:'Special',
pp:15,
power:55,
accuracy:95,
description:"Decreases opponent's Speed by one stage.",
probability:100,
},
'Imprison':{
type:'Psychic',
category:'Status',
pp:10,
description:'Opponent is unable to use moves that the user also knows.',
},
'Incinerate':{
type:'Fire',
category:'Special',
pp:15,
power:30,
accuracy:100,
description:"Destroys the target's held berry.",
},
'Inferno':{
type:'Fire',
category:'Special',
pp:5,
power:100,
accuracy:50,
description:'Burns the target, if it hits.',
probability:100,
},
'Ingrain':{
type:'Grass',
category:'Status',
pp:20,
description:'User restores HP each turn. User cannot escape/switch.',
},
'Iron Defense':{
type:'Steel',
category:'Status',
pp:15,
description:"Increases the user's Defense by two stages.",
},
'Iron Head':{
type:'Steel',
category:'Physical',
pp:15,
power:80,
accuracy:100,
description:'May cause flinching.',
probability:30,
},
'Iron Tail':{
type:'Steel',
category:'Physical',
pp:15,
power:100,
accuracy:75,
tm:'TM23',
description:"May decrease opponent's Defense by one stage.",
probability:30,
},
'Judgment':{
type:'Normal',
category:'Special',
pp:10,
power:100,
accuracy:100,
description:'Type depends on the Arceus Plate being held.',
},
'Jump Kick':{
type:'Fighting',
category:'Physical',
pp:25,
power:85,
accuracy:95,
description:'If it misses, the user loses half their HP.',
},
'Karate Chop':{
type:'Fighting',
category:'Physical',
pp:25,
power:50,
accuracy:100,
description:'High Critical-Hit ratio.',
},
'Kinesis':{
type:'Psychic',
category:'Status',
pp:15,
accuracy:80,
description:"Decreases opponent's Accuracy by one stage, if it hits.",
},
'Knock Off':{
type:'Dark',
category:'Physical',
pp:20,
power:20,
accuracy:100,
description:'Opponent cannot use its hold item for the duration of the battle.',
},
'Last Resort':{
type:'Normal',
category:'Physical',
pp:5,
power:140,
accuracy:100,
description:'Can only be used after all other moves are used.',
},
'Lava Plume':{
type:'Fire',
category:'Special',
pp:15,
power:80,
accuracy:100,
description:'May cause a burn.',
probability:30,
},
'Leaf Blade':{
type:'Grass',
category:'Physical',
pp:15,
power:90,
accuracy:100,
description:'High Critcal-Hit ratio.',
},
'Leaf Storm':{
type:'Grass',
category:'Special',
pp:5,
power:140,
accuracy:90,
description:"Decreases user's Special Attack by two stages.",
},
'Leaf Tornado':{
type:'Grass',
category:'Special',
pp:10,
power:65,
accuracy:90,
description:"May lower the target's Accuracy by one level.",
probability:50,
},
'Leech Life':{
type:'Bug',
category:'Physical',
pp:15,
power:20,
accuracy:100,
description:'User recovers half of the damage inflicted on the opponent.',
},
'Leech Seed':{
type:'Grass',
category:'Status',
pp:10,
accuracy:90,
description:'User steals HP from opponent each turn.',
},
'Leer':{
type:'Normal',
category:'Status',
pp:30,
accuracy:100,
description:"Decreases opponent's Defense by one stage.",
},
'Lick':{
type:'Ghost',
category:'Physical',
pp:30,
power:20,
accuracy:100,
description:'May cause paralysis.',
probability:30,
},
'Light Screen':{
type:'Psychic',
category:'Status',
pp:30,
tm:'TM16',
description:"User's party receives 1/2 damage from Sp. Attacks for 5 turns.",
},
'Lock-on':{
type:'Normal',
category:'Status',
pp:5,
description:'The next move the user uses is guaranteed to hit.',
},
'Lovely Kiss':{
type:'Normal',
category:'Status',
pp:10,
accuracy:75,
description:'Puts the opponent to sleep, if it hits.',
},
'Low Kick':{
type:'Fighting',
category:'Status',
pp:20,
accuracy:100,
description:'The heavier the opponent, the stronger the attack.',
},
'Low Sweep':{
type:'Fighting',
category:'Physical',
pp:20,
power:60,
accuracy:100,
description:"Lowers the target's Speed by one level.",
probability:100,
},
'Lucky Chant':{
type:'Normal',
category:'Status',
pp:30,
description:'Opponent cannot land Critical Hits for 5 turns.',
},
'Lunar Dance':{
type:'Psychic',
category:'Status',
pp:10,
description:'The user faints but the next Pokemon released is fully healed.',
},
'Luster Purge':{
type:'Psychic',
category:'Special',
pp:5,
power:70,
accuracy:100,
description:"May decrease opponent's Special Defense by one stage.",
},
'Mach Punch':{
type:'Fighting',
category:'Physical',
pp:30,
power:40,
accuracy:100,
description:'User goes first.',
},
'Magic Coat':{
type:'Psychic',
category:'Status',
pp:15,
description:'Any special move is reflected back to the attacker.',
},
'Magic Room':{
type:'Psychic',
category:'Status',
pp:10,
description:'Suppresses the effects of held items for five turns.',
},
'Magical Leaf':{
type:'Grass',
category:'Special',
pp:20,
power:60,
description:'Cannot miss, regardless of Accuracy or Evasiveness.',
},
'Magma Storm':{
type:'Fire',
category:'Special',
pp:5,
power:120,
accuracy:75,
description:'Opponent cannot escape/switch.',
},
'Magnet Bomb':{
type:'Steel',
category:'Physical',
pp:20,
power:60,
description:'Cannot miss, regardless of Accuracy or Evasiveness.',
},
'Magnet Rise':{
type:'Electric',
category:'Status',
pp:10,
description:'User becomes immune to Ground-type moves for 5 turns.',
},
'Magnitude':{
type:'Ground',
category:'Physical',
pp:30,
accuracy:100,
description:'Hits with random power.',
},
'Me First':{
type:'Normal',
category:'Status',
pp:20,
description:"User goes first with the opponent's attack at 1.5x power.",
},
'Mean Look':{
type:'Normal',
category:'Status',
pp:5,
description:'Opponent cannot escape/switch.',
},
'Meditate':{
type:'Psychic',
category:'Status',
pp:40,
description:"Increases user's Attack by one stage.",
},
'Mega Drain':{
type:'Grass',
category:'Special',
pp:15,
power:40,
accuracy:100,
description:'User recovers 1/2 of the damage inflicted onto the opponent.',
},
'Mega Kick':{
type:'Normal',
category:'Physical',
pp:5,
power:120,
accuracy:75,
},
'Mega Punch':{
type:'Normal',
category:'Physical',
pp:20,
power:80,
accuracy:85,
},
'Megahorn':{
type:'Bug',
category:'Physical',
pp:10,
power:120,
accuracy:85,
},
'Memento':{
type:'Dark',
category:'Status',
pp:10,
accuracy:100,
description:"User faints, opponent's Attack is dropped to the lowest stage.",
},
'Metal Burst':{
type:'Steel',
category:'Physical',
pp:10,
accuracy:100,
description:"Deals damage equal to 1.5x opponent's attack.",
},
'Metal Claw':{
type:'Steel',
category:'Physical',
pp:35,
power:50,
accuracy:95,
description:"May increase the user's Attack by one stage.",
probability:10,
},
'Metal Sound':{
type:'Steel',
category:'Status',
pp:40,
accuracy:85,
description:"Decreases opponent's Special Defense by two stages.",
},
'Meteor Mash':{
type:'Steel',
category:'Physical',
pp:10,
power:100,
accuracy:85,
description:"May increase user's Attack by one stage.",
probability:20,
},
'Metronome':{
type:'Normal',
category:'Status',
pp:10,
description:'User performs any move in the game at random.',
},
'Milk Drink':{
type:'Normal',
category:'Status',
pp:10,
description:'User recoves 50% of its maximum HP.',
},
'Mimic':{
type:'Normal',
category:'Status',
pp:10,
description:"Replaces this move with the opponent's last move, for the battle.",
},
'Mind Reader':{
type:'Psychic',
category:'Status',
pp:5,
description:"User's next attack is guaranteed to hit.",
},
'Minimize':{
type:'Normal',
category:'Status',
pp:20,
description:"Increases user's Evasiveness by one stage.",
},
'Miracle Eye':{
type:'Psychic',
category:'Status',
pp:40,
description:"Resets opponent's Evasiveness, removes Dark's Psychic immunity.",
},
'Mirror Coat':{
type:'Psychic',
category:'Special',
pp:20,
accuracy:100,
description:'When hit by a Special Attack, user strikes back with 2x power.',
},
'Mirror Move':{
type:'Flying',
category:'Status',
pp:20,
description:"User performs the opponent's last move.",
},
'Mirror Shot':{
type:'Steel',
category:'Special',
pp:10,
power:65,
accuracy:85,
description:"May decrease opponent's Accuracy by one stage.",
},
'Mist':{
type:'Ice',
category:'Status',
pp:30,
description:"User's stats cannot be changed for a period of time.",
},
'Mist Ball':{
type:'Psychic',
category:'Special',
pp:5,
power:70,
accuracy:100,
description:"Likely to decrease opponent's Special Attack by one stage.",
probability:50,
},
'Moonlight':{
type:'Normal',
category:'Status',
pp:5,
description:'User recovers HP. Amount varies with the weather.',
},
'Morning Sun':{
type:'Normal',
category:'Status',
pp:5,
description:'User recovers HP. Amount varies with the weather.',
},
'Mud Bomb':{
type:'Ground',
category:'Special',
pp:10,
power:65,
accuracy:85,
description:"May decrease opponent's Accuracy by one stage.",
probability:30,
},
'Mud Shot':{
type:'Ground',
category:'Special',
pp:15,
power:55,
accuracy:95,
description:"Decreases opponent's Speed by one stage.",
probability:100,
},
'Mud Sport':{
type:'Ground',
category:'Status',
pp:15,
description:'Weakens the power of Electric-type moves.',
},
'Mud-Slap':{
type:'Ground',
category:'Special',
pp:10,
power:20,
accuracy:100,
description:"Lowers opponent's accuracy by one stage",
probability:100,
},
'Muddy Water':{
type:'Water',
category:'Special',
pp:10,
power:95,
accuracy:85,
description:"May decrease opponent's Accuracy by one stage.",
probability:30,
},
'Nasty Plot':{
type:'Dark',
category:'Status',
pp:20,
description:"Increases the user's Special Attack by two stages.",
},
'Natural Gift':{
type:'Normal',
category:'Physical',
pp:15,
accuracy:100,
tm:'TM83',
description:"The type and power depends on the user's held berry.",
},
'Nature Power':{
type:'Normal',
category:'Status',
pp:20,
description:'Uses a certain move based on the current location.',
},
'Needle Arm':{
type:'Grass',
category:'Physical',
pp:15,
power:60,
accuracy:100,
description:'May cause flinching.',
probability:30,
},
'Night Daze':{
type:'Dark',
category:'Special',
pp:10,
power:85,
accuracy:95,
description:"May lower the target's Accuracy by one level.",
probability:40,
},
'Night Shade':{
type:'Ghost',
category:'Special',
pp:15,
accuracy:100,
description:"Inflicts damage equal to user's level.",
},
'Night Slash':{
type:'Dark',
category:'Physical',
pp:15,
power:70,
accuracy:100,
description:'High Critical-Hit ratio.',
},
'Nightmare':{
type:'Ghost',
category:'Special',
pp:15,
accuracy:100,
description:'The sleeping opponent loses 25% of its max HP each turn.',
},
'Octazooka':{
type:'Water',
category:'Special',
pp:10,
power:65,
accuracy:85,
description:"Likely to decrease opponent's Accuracy by one stage.",
probability:50,
},
'Odor Sleuth':{
type:'Normal',
category:'Status',
pp:40,
description:"Resets opponent's Evasiveness, Normal-type and Fighting-type attacks can now hit Ghosts, and Ghost-type attacks hit Normal.",
},
'Ominous Wind':{
type:'Ghost',
category:'Special',
pp:5,
power:60,
accuracy:100,
description:'May increase all stats of the user by one stage each.',
probability:10,
},
'Outrage':{
type:'Dragon',
category:'Physical',
pp:15,
power:120,
accuracy:100,
description:'User attacks for 2-3 turns and then becomes confused.',
},
'Overheat':{
type:'Fire',
category:'Special',
pp:5,
power:140,
accuracy:90,
tm:'TM50',
description:"Decreases user's Special Attack by two stages.",
},
'Pain Split':{
type:'Normal',
category:'Status',
pp:20,
description:"The user's and opponent's HP becomes the average of both.",
},
'Pay Day':{
type:'Normal',
category:'Physical',
pp:20,
power:40,
accuracy:100,
description:'A small amount of money is gained after the battle resolves.',
},
'Payback':{
type:'Dark',
category:'Physical',
pp:10,
power:50,
accuracy:100,
tm:'TM66',
description:'Power doubles if the user was attacked first.',
},
'Peck':{
type:'Flying',
category:'Physical',
pp:35,
power:35,
accuracy:100,
},
'Perish Song':{
type:'Normal',
category:'Status',
pp:5,
description:'Any Pokemon in play when this attack is used faints in 3 turns.',
},
'Petal Dance':{
type:'Grass',
category:'Special',
pp:10,
power:120,
accuracy:100,
description:'User attacks for 2-3 turns but then becomes confused.',
},
'Pin Missile':{
type:'Bug',
category:'Physical',
pp:20,
power:14,
accuracy:85,
description:'Hits 2-5 times in one turn.',
},
'Pluck':{
type:'Flying',
category:'Physical',
pp:20,
power:60,
accuracy:100,
tm:'TM88',
description:'If the opponent is holding a berry, its effect is stolen by user.',
},
'Poison Fang':{
type:'Poison',
category:'Physical',
pp:15,
power:50,
accuracy:100,
description:'May cause poison that gets worse each turn.',
probability:30,
},
'Poison Gas':{
type:'Poison',
category:'Status',
pp:40,
accuracy:85,
description:'Poisons the opponent, if it hits.',
},
'Poison Jab':{
type:'Poison',
category:'Physical',
pp:20,
power:80,
accuracy:100,
tm:'TM84',
description:'May poison the opponent.',
probability:30,
},
'Poison Sting':{
type:'Poison',
category:'Physical',
pp:35,
power:15,
accuracy:100,
description:'May poison the opponent.',
probability:30,
},
'Poison Tail':{
type:'Poison',
category:'Physical',
pp:25,
power:50,
accuracy:100,
description:'High Critical-Hit ratio. May poison the opponent.',
probability:10,
},
'Poisonpowder':{
type:'Poison',
category:'Status',
pp:35,
accuracy:75,
description:'Poisons the opponent, if it hits.',
},
'Pound':{
type:'Normal',
category:'Physical',
pp:35,
power:40,
accuracy:100,
},
'Powder Snow':{
type:'Ice',
category:'Special',
pp:25,
power:40,
accuracy:100,
description:'May cause freezing.',
probability:10,
},
'Power Gem':{
type:'Rock',
category:'Special',
pp:20,
power:70,
accuracy:100,
},
'Power Split':{
type:'Psychic',
category:'Status',
pp:10,
description:'Averages Attack and Special Attack with the target.',
},
'Power Swap':{
type:'Psychic',
category:'Status',
pp:10,
description:'User and opponent swap Attack and Special Attack.',
},
'Power Trick':{
type:'Psychic',
category:'Status',
pp:10,
description:"User's own Attack and Defense switch.",
},
'Power Whip':{
type:'Grass',
category:'Physical',
pp:10,
power:120,
accuracy:85,
},
'Present':{
type:'Normal',
category:'Physical',
pp:15,
accuracy:90,
description:'Either deals damage or heals.',
},
'Protect':{
type:'Normal',
category:'Status',
pp:10,
tm:'TM17',
description:"User is not affected by opponent's move.",
},
'Psybeam':{
type:'Psychic',
category:'Special',
pp:20,
power:65,
accuracy:100,
description:'May confuse the opponent.',
probability:10,
},
'Psych Up':{
type:'Normal',
category:'Status',
pp:10,
tm:'TM77',
description:"Copies the opponent's stat changes.",
},
'Psychic':{
type:'Psychic',
category:'Special',
pp:10,
power:90,
accuracy:100,
tm:'TM29',
description:"May decreases the opponent's Special Defense by one stage.",
probability:10,
},
'Psycho Boost':{
type:'Psychic',
category:'Special',
pp:5,
power:140,
accuracy:90,
description:"Decreases user's Special Attack by two stages.",
},
'Psycho Cut':{
type:'Psychic',
category:'Physical',
pp:20,
power:70,
accuracy:100,
description:'High Critical-Hit ratio.',
},
'Psycho Shift':{
type:'Psychic',
category:'Status',
pp:10,
accuracy:90,
description:"Gives the opponent the user's status condition, if it hits.",
},
'Psyshock':{
type:'Psychic',
category:'Special',
pp:10,
power:80,
accuracy:100,
description:"Inflicts damage based on the target's Defense, not Special Defense.",
},
'Psystrike':{
type:'Psychic',
category:'Special',
pp:10,
power:100,
accuracy:100,
description:"Inflicts damage based on the target's Defense, not Special Defense.",
},
'Psywave':{
type:'Psychic',
category:'Special',
pp:15,
accuracy:80,
description:"Inflicts damage 50-150% of user's level.",
},
'Punishment':{
type:'Dark',
category:'Physical',
pp:5,
accuracy:100,
description:"Power depends on opponent's stats.",
},
'Pursuit':{
type:'Dark',
category:'Physical',
pp:20,
power:40,
accuracy:100,
description:'Double power if the opponent is switching out.',
},
'Quash':{
type:'Dark',
category:'Status',
pp:15,
accuracy:100,
description:'Makes the target act last this turn.',
},
'Quick Attack':{
type:'Normal',
category:'Physical',
pp:30,
power:40,
accuracy:100,
description:'User goes first.',
},
'Quick Guard':{
type:'Fighting',
category:'Status',
pp:15,
description:"Fast moves won't damage the user or its teammates.",
},
'Quiver Dance':{
type:'Bug',
category:'Status',
pp:20,
description:"Raises the user's Special Attack, Special Defense and Speed.",
},
'Rage':{
type:'Normal',
category:'Physical',
pp:20,
power:20,
accuracy:100,
description:"Increases user's Attack by one stage when hit.",
},
'Rage Powder':{
type:'Bug',
category:'Status',
pp:20,
description:'Forces attacks to hit user, not team-mates.',
},
'Rain Dance':{
type:'Water',
category:'Status',
pp:5,
tm:'TM18',
description:'Causes the weather to change to rain for 5 turns.',
},
'Rapid Spin':{
type:'Normal',
category:'Physical',
pp:40,
power:20,
accuracy:100,
description:'Removes the effects of trap moves',
},
'Razor Leaf':{
type:'Grass',
category:'Physical',
pp:25,
power:55,
accuracy:95,
description:'High Critical-Hit ratio.',
},
'Razor Shell':{
type:'Water',
category:'Physical',
pp:10,
power:75,
accuracy:95,
description:"May lower the target's Defense by one level.",
probability:50,
},
'Razor Wind':{
type:'Normal',
category:'Special',
pp:10,
power:80,
accuracy:100,
description:'Immobile on the first turn, attacks on the second turn. High Critical-Hit ratio.',
},
'Recover':{
type:'Normal',
category:'Status',
pp:10,
description:'User recovers 50% of its max HP.',
},
'Recycle':{
type:'Normal',
category:'Status',
pp:10,
tm:'TM67',
description:"User's used hold item is restored.",
},
'Reflect':{
type:'Psychic',
category:'Status',
pp:20,
tm:'TM33',
description:"User's party receives 1/2 damage from Ph. Attacks for 5 turns.",
},
'Reflect Type':{
type:'Normal',
category:'Status',
pp:15,
description:"User becomes the target's type.",
},
'Refresh':{
type:'Normal',
category:'Status',
pp:20,
description:'Cures paralysis, poison, and burns.',
},
'Relic Song':{
type:'Normal',
category:'Special',
pp:10,
power:75,
accuracy:100,
description:'May put the target to sleep.',
probability:10,
},
'Rest':{
type:'Psychic',
category:'Status',
pp:10,
tm:'TM44',
description:'User sleeps for 2 turns, but user is fully healed.',
},
'Retaliate':{
type:'Normal',
category:'Physical',
pp:5,
power:70,
accuracy:100,
description:'Inflicts double damage if a teammate fainted on the last turn.',
},
'Return':{
type:'Normal',
category:'Physical',
pp:20,
accuracy:100,
tm:'TM27',
description:"Power increases with user's Happiness.",
},
'Revenge':{
type:'Fighting',
category:'Physical',
pp:10,
power:60,
accuracy:100,
description:'Power increases if user was hit first.',
},
'Reversal':{
type:'Fighting',
category:'Physical',
pp:15,
accuracy:100,
description:"The lower the user's HP, the higher the power.",
},
'Roar':{
type:'Normal',
category:'Status',
pp:20,
accuracy:100,
tm:'TM05',
description:'In battles, the opponent switches. In the wild, the Pokemon runs.',
},
'Roar of Time':{
type:'Dragon',
category:'Special',
pp:5,
power:150,
accuracy:90,
description:'The user cannot move in the following turn.',
},
'Rock Blast':{
type:'Rock',
category:'Physical',
pp:10,
power:25,
accuracy:90,
description:'Hits 2-5 times in one turn.',
},
'Rock Climb':{
type:'Normal',
category:'Physical',
pp:20,
power:90,
accuracy:85,
tm:'HM08',
description:'May cause confusion.',
probability:20,
},
'Rock Polish':{
type:'Rock',
category:'Status',
pp:20,
tm:'TM69',
description:"Increases the user's Speed by two stages.",
},
'Rock Slide':{
type:'Rock',
category:'Physical',
pp:10,
power:75,
accuracy:90,
tm:'TM80',
description:'May cause flinching, if it hits.',
probability:30,
},
'Rock Smash':{
type:'Fighting',
category:'Physical',
pp:15,
power:40,
accuracy:100,
tm:'HM06',
description:"Likely to decrease the opponent's Defense by one stage.",
probability:50,
},
'Rock Throw':{
type:'Rock',
category:'Physical',
pp:15,
power:50,
accuracy:90,
},
'Rock Tomb':{
type:'Rock',
category:'Physical',
pp:10,
power:50,
accuracy:80,
tm:'TM39',
description:"Decreases the opponent's Speed by one stage, if it hits.",
probability:100,
},
'Rock Wrecker':{
type:'Rock',
category:'Physical',
pp:5,
power:150,
accuracy:90,
description:'The user cannot move in the following turn.',
},
'Role Play':{
type:'Psychic',
category:'Status',
pp:15,
description:"User copies the opponent's Ability.",
},
'Rolling Kick':{
type:'Fighting',
category:'Physical',
pp:15,
power:60,
accuracy:85,
description:'May cause flinching.',
probability:30,
},
'Rollout':{
type:'Rock',
category:'Physical',
pp:20,
power:30,
accuracy:90,
description:'An attack lasting for 5 turns that grows in power.',
},
'Roost':{
type:'Flying',
category:'Status',
pp:10,
tm:'TM51',
description:'User recovers 50% of its max HP. Flying-type users are not immune to Ground-type moves immediately following this move.',
},
'Round':{
type:'Normal',
category:'Special',
pp:15,
power:60,
accuracy:100,
description:'Power increases each turn if multiple Pokemon in the team also use it.',
},
'Sacred Fire':{
type:'Fire',
category:'Physical',
pp:5,
power:100,
accuracy:95,
description:'Likely to cause a burn.',
probability:50,
},
'Sacred Sword':{
type:'Fighting',
category:'Physical',
pp:20,
power:90,
accuracy:100,
description:"Ignores the target's stat changes.",
},
'Safeguard':{
type:'Normal',
category:'Status',
pp:25,
tm:'TM20',
description:"The user's party is protected from status conditions.",
},
'Sand Tomb':{
type:'Ground',
category:'Physical',
pp:15,
power:35,
accuracy:85,
description:'Damages opponent for 2-5 turns, opponent cannot switch/escape.',
},
'Sand-attack':{
type:'Ground',
category:'Status',
pp:15,
accuracy:100,
description:"Decreases the opponent's Accuracy by one stage.",
},
'Sandstorm':{
type:'Rock',
category:'Status',
pp:10,
tm:'TM37',
description:'Non Rock, Ground and Steel types are damaged for 5 turns.',
},
'Scald':{
type:'Water',
category:'Special',
pp:15,
power:80,
accuracy:100,
description:'May burn the target.',
probability:30,
},
'Scary Face':{
type:'Normal',
category:'Status',
pp:10,
accuracy:100,
description:"Sharply lowers opponent's Speed.",
},
'Scratch':{
type:'Normal',
category:'Physical',
pp:35,
power:40,
accuracy:100,
},
'Screech':{
type:'Normal',
category:'Status',
pp:40,
accuracy:85,
description:"Decreases the opponent's Defense by two stages, if it hits.",
},
'Searing Shot':{
type:'Fire',
category:'Special',
pp:5,
power:100,
accuracy:100,
description:'May burn the target.',
probability:30,
},
'Secret Power':{
type:'Normal',
category:'Physical',
pp:20,
power:70,
accuracy:100,
tm:'TM43',
description:'Effects of the attack vary with the location.',
probability:30,
},
'Secret Sword':{
type:'Fighting',
category:'Special',
pp:10,
power:85,
accuracy:100,
description:"Inflicts damage based on the target's Defense, not Special Defense.",
},
'Seed Bomb':{
type:'Grass',
category:'Physical',
pp:15,
power:80,
accuracy:100,
},
'Seed Flare':{
type:'Grass',
category:'Special',
pp:5,
power:120,
accuracy:85,
description:"May decrease the opponent's Special Defense by one stage.",
probability:40,
},
'Seismic Toss':{
type:'Fighting',
category:'Physical',
pp:20,
accuracy:100,
description:"Inflicts damage equal to user's level.",
},
'Selfdestruct':{
type:'Normal',
category:'Physical',
pp:5,
power:200,
accuracy:100,
description:'User faints.',
},
'Shadow Ball':{
type:'Ghost',
category:'Special',
pp:15,
power:80,
accuracy:100,
tm:'TM30',
description:"May decrease opponent's Special Defense.",
probability:20,
},
'Shadow Claw':{
type:'Ghost',
category:'Physical',
pp:15,
power:70,
accuracy:100,
tm:'TM65',
description:'High Critical-Hit ratio.',
},
'Shadow Force':{
type:'Ghost',
category:'Physical',
pp:5,
power:120,
accuracy:100,
description:'Disappears on the 1st turn, attacks on the 2nd turn.',
},
'Shadow Punch':{
type:'Ghost',
category:'Physical',
pp:20,
power:60,
description:'Cannot miss, regardless of Accuracy and Evasiveness.',
},
'Shadow Sneak':{
type:'Ghost',
category:'Physical',
pp:30,
power:40,
accuracy:100,
description:'User goes first.',
},
'Sharpen':{
type:'Normal',
category:'Status',
pp:30,
description:"Increases the user's Attack by one stage.",
},
'Sheer Cold':{
type:'Ice',
category:'Special',
pp:5,
accuracy:30,
description:'An instant 1-hit KO, if it hits.',
},
'Shell Smash':{
type:'Normal',
category:'Status',
pp:15,
description:"Sharply raises user's Attack, Special Attack and Speed but lowers Defense and Special Defense.",
},
'Shift Gear':{
type:'Steel',
category:'Status',
pp:10,
description:'Raises Attack and sharply raises Speed.',
},
'Shock Wave':{
type:'Electric',
category:'Special',
pp:20,
power:60,
tm:'TM34',
description:'Cannot miss, regardless of Accuracy and Evasiveness.',
},
'Signal Beam':{
type:'Bug',
category:'Special',
pp:15,
power:75,
accuracy:100,
description:'May cause confusion.',
probability:10,
},
'Silver Wind':{
type:'Bug',
category:'Special',
pp:5,
power:60,
accuracy:100,
tm:'TM62',
description:"May increase all of the user's stats by one stage each.",
probability:10,
},
'Simple Beam':{
type:'Normal',
category:'Status',
pp:15,
accuracy:100,
description:"Changes target's ability to Simple.",
},
'Sing':{
type:'Normal',
category:'Status',
pp:15,
accuracy:55,
description:'Puts the opponent to sleep, if it hits.',
probability:100,
},
'Sketch':{
type:'Normal',
category:'Status',
pp:1,
description:"Permanently copies the opponent's last move.",
},
'Skill Swap':{
type:'Psychic',
category:'Status',
pp:10,
tm:'TM48',
description:'The user swaps Abilities with the opponent.',
},
'Skull Bash':{
type:'Normal',
category:'Physical',
pp:15,
power:100,
accuracy:100,
description:"Increases user's Defense one stage in the 1st turn, attacks in the 2nd turn.",
probability:100,
},
'Sky Attack':{
type:'Flying',
category:'Physical',
pp:5,
power:140,
accuracy:90,
description:'User cannot move in the 1st turn, attacks 2nd turn. May cause flinching.',
probability:30,
},
'Sky Drop':{
type:'Flying',
category:'Physical',
pp:10,
power:60,
accuracy:100,
description:'Tosses the target into the air on first turn; Drops them on the second.',
},
'Sky Uppercut':{
type:'Fighting',
category:'Physical',
pp:15,
power:85,
accuracy:90,
description:'Hits the opponent, even during Fly.',
},
'Slack Off':{
type:'Normal',
category:'Status',
pp:10,
description:'User recovers 50% of its max HP.',
},
'Slam':{
type:'Normal',
category:'Physical',
pp:20,
power:80,
accuracy:75,
},
'Slash':{
type:'Normal',
category:'Physical',
pp:20,
power:70,
accuracy:100,
description:'High Critical-Hit ratio.',
},
'Sleep Powder':{
type:'Grass',
category:'Status',
pp:15,
accuracy:75,
description:'Puts the opponent to sleep, if it hits.',
},
'Sleep Talk':{
type:'Normal',
category:'Status',
pp:10,
tm:'TM82',
description:'User performs one of its own moves while sleeping.',
},
'Sludge':{
type:'Poison',
category:'Special',
pp:20,
power:65,
accuracy:100,
description:'May poison the opponent.',
probability:30,
},
'Sludge Bomb':{
type:'Poison',
category:'Special',
pp:10,
power:90,
accuracy:100,
tm:'TM36',
description:'May poison the opponent.',
probability:30,
},
'Sludge Wave':{
type:'Poison',
category:'Special',
pp:10,
power:95,
accuracy:100,
description:'May poison the target.',
probability:10,
},
'Smack Down':{
type:'Rock',
category:'Physical',
pp:15,
power:50,
accuracy:100,
description:'Makes Flying-type pokemon vulnerable to Ground moves.',
probability:100,
},
'Smellingsalt':{
type:'Normal',
category:'Special',
pp:10,
power:60,
accuracy:100,
description:'Power increases when used on a paralyzed opponent, but cures it.',
},
'Smog':{
type:'Poison',
category:'Special',
pp:20,
power:20,
accuracy:70,
description:'May poison the opponent.',
probability:40,
},
'Smokescreen':{
type:'Normal',
category:'Status',
pp:20,
accuracy:100,
description:"Decreases the opponent's Accuracy by one stage.",
},
'Snarl':{
type:'Dark',
category:'Special',
pp:15,
power:55,
accuracy:95,
description:"Lowers the target's Special Attack by one level.",
probability:100,
},
'Snatch':{
type:'Dark',
category:'Status',
pp:10,
tm:'TM49',
description:"User steals the effects of the opponent's next move.",
},
'Snore':{
type:'Normal',
category:'Special',
pp:15,
power:40,
accuracy:100,
description:'Can only be used while the user is sleeping.',
},
'Soak':{
type:'Water',
category:'Status',
pp:20,
accuracy:100,
description:"Changes the target's type to water.",
},
'Softboiled':{
type:'Normal',
category:'Status',
pp:10,
description:'User recovers 50% of its max HP.',
},
'Solarbeam':{
type:'Grass',
category:'Special',
pp:10,
power:120,
accuracy:100,
tm:'TM22',
description:'User cannot move in the 1st turn, attacks in the 2nd turn.',
},
'Sonicboom':{
type:'Normal',
category:'Special',
pp:20,
accuracy:90,
description:'Always inflicts 20 HP.',
},
'Spacial Rend':{
type:'Dragon',
category:'Special',
pp:5,
power:100,
accuracy:95,
description:'High Critical-Hit ratio.',
},
'Spark':{
type:'Electric',
category:'Physical',
pp:20,
power:65,
accuracy:100,
description:'May cause paralysis.',
probability:30,
},
'Spider Web':{
type:'Bug',
category:'Status',
pp:10,
description:'Opponent cannot escape/switch.',
},
'Spike Cannon':{
type:'Normal',
category:'Physical',
pp:15,
power:20,
accuracy:100,
description:'Hits 2-5 times in one turn.',
},
'Spikes':{
type:'Ground',
category:'Status',
pp:20,
description:'Hurts opponents when they switch into battle.',
},
'Spit Up':{
type:'Normal',
category:'Special',
pp:10,
accuracy:100,
description:'Power depends on how many times the user performed Stockpile.',
},
'Spite':{
type:'Ghost',
category:'Status',
pp:10,
accuracy:100,
description:"The opponent's last move loses 2-5 PP.",
},
'Splash':{
type:'Normal',
category:'Status',
pp:40,
description:"Doesn't do ANYTHING.",
},
'Spore':{
type:'Grass',
category:'Status',
pp:15,
accuracy:100,
description:'Puts the opponent to sleep.',
probability:100,
},
'Stealth Rock':{
type:'Rock',
category:'Status',
pp:20,
tm:'TM76',
description:'Damages opponent when they switch into battle.',
},
'Steamroller':{
type:'Bug',
category:'Physical',
pp:20,
power:65,
accuracy:100,
description:'May make the target flinch.',
probability:30,
},
'Steel Wing':{
type:'Steel',
category:'Physical',
pp:25,
power:70,
accuracy:90,
tm:'TM47',
description:"May increases user's Defense by one stage.",
probability:10,
},
'Stockpile':{
type:'Normal',
category:'Status',
pp:20,
description:"Temporarily increases user's Defense by one stage. To be used with Spit Up and Swallow.",
},
'Stomp':{
type:'Normal',
category:'Physical',
pp:20,
power:65,
accuracy:100,
description:'May cause flinching.',
probability:30,
},
'Stone Edge':{
type:'Rock',
category:'Physical',
pp:5,
power:100,
accuracy:80,
tm:'TM71',
description:'High Critical-Hit ratio.',
},
'Stored Power':{
type:'Psychic',
category:'Special',
pp:10,
power:20,
accuracy:100,
description:"Power rises the more the user's stats have been raised.",
},
'Storm Throw':{
type:'Fighting',
category:'Physical',
pp:10,
power:40,
accuracy:100,
description:'Always results in a critical hit.',
},
'Strength':{
type:'Normal',
category:'Physical',
pp:15,
power:80,
accuracy:100,
tm:'HM04',
},
'String Shot':{
type:'Bug',
category:'Status',
pp:40,
accuracy:95,
description:"Decreases opponent's Speed by one stage.",
},
'Struggle':{
type:'Normal',
category:'Physical',
pp:999999,
power:50,
accuracy:100,
description:'Only usable when all PP are gone. Hurts the user.',
},
'Struggle Bug':{
type:'Bug',
category:'Special',
pp:20,
power:30,
accuracy:100,
description:"Lowers the target's Special Attack by one level.",
probability:100,
},
'Stun Spore':{
type:'Grass',
category:'Status',
pp:30,
accuracy:75,
description:'Causes paralysis, if it hits.',
},
'Submission':{
type:'Fighting',
category:'Physical',
pp:25,
power:80,
accuracy:80,
description:'User receives recoil damage.',
},
'Substitute':{
type:'Normal',
category:'Status',
pp:10,
tm:'TM90',
description:'User loses 1/4 of its max HP, but can take hits without losing HP for awhile.',
},
'Sucker Punch':{
type:'Dark',
category:'Physical',
pp:5,
power:80,
accuracy:100,
description:"User goes first, but won't work if opponent doesn't use an attacking move.",
},
'Sunny Day':{
type:'Fire',
category:'Status',
pp:5,
tm:'TM11',
description:'Changes the weather to sunny.',
},
'Super Fang':{
type:'Normal',
category:'Physical',
pp:10,
accuracy:90,
description:"Always takes off half of the opponent's HP.",
},
'Superpower':{
type:'Fighting',
category:'Physical',
pp:5,
power:120,
accuracy:100,
description:"Decreases user's Attack and Defense by one stage each.",
},
'Supersonic':{
type:'Normal',
category:'Status',
pp:20,
accuracy:55,
description:'Causes confusion, if it hits.',
},
'Surf':{
type:'Water',
category:'Special',
pp:15,
power:95,
accuracy:100,
tm:'HM03',
},
'Swagger':{
type:'Normal',
category:'Status',
pp:15,
accuracy:90,
tm:'TM87',
description:'Opponent becomes confused, but its Attack is raised by 2 stages.',
},
'Swallow':{
type:'Normal',
category:'Status',
pp:10,
description:'The more times the user has performed Stockpile, the more HP is recovered.',
},
'Sweet Kiss':{
type:'Normal',
category:'Status',
pp:10,
accuracy:75,
description:'Causes confusion, if it hits.',
},
'Sweet Scent':{
type:'Normal',
category:'Status',
pp:20,
description:"Decreases opponent's Evasiveness by one stage.",
},
'Swift':{
type:'Normal',
category:'Special',
pp:20,
power:60,
description:'Cannot miss, regardless of Accuracy and Evasiveness.',
},
'Switcheroo':{
type:'Dark',
category:'Status',
pp:15,
accuracy:100,
description:'Swaps held items with the opponent.',
},
'Swords Dance':{
type:'Normal',
category:'Status',
pp:30,
tm:'TM75',
description:"Increases the user's Attack by two stages.",
},
'Synchronoise':{
type:'Psychic',
category:'Special',
pp:15,
power:70,
accuracy:100,
description:'Hits any Pokemon that shares a type with the user.',
},
'Synthesis':{
type:'Grass',
category:'Status',
pp:5,
description:'User recovers HP. Amount varies with the weather.',
},
'Tackle':{
type:'Normal',
category:'Physical',
pp:35,
power:50,
accuracy:100,
},
'Tail Glow':{
type:'Bug',
category:'Status',
pp:20,
description:"Drastically increases user's Special Attack.",
},
'Tail Slap':{
type:'Normal',
category:'Physical',
pp:10,
power:25,
accuracy:85,
description:'Hits 2-5 times in one turn.',
},
'Tail Whip':{
type:'Normal',
category:'Status',
pp:30,
accuracy:100,
description:"Decreases opponent's Defense by one stage.",
},
'Tailwind':{
type:'Flying',
category:'Status',
pp:30,
description:"The user's party's Speed is increased by one stage for 5 turns.",
},
'Take Down':{
type:'Normal',
category:'Physical',
pp:20,
power:90,
accuracy:85,
description:'User receives recoil damage.',
},
'Taunt':{
type:'Dark',
category:'Status',
pp:20,
accuracy:100,
tm:'TM12',
description:'Opponent can only use moves that attack.',
},
'Techno Blast':{
type:'Normal',
category:'Special',
pp:5,
power:85,
accuracy:100,
description:'If the user is holding a plate, the damage inflicted will match it.',
},
'Teeter Dance':{
type:'Normal',
category:'Status',
pp:20,
accuracy:100,
description:'All Pokemon on the field become confused.',
},
'Telekinesis':{
type:'Psychic',
category:'Status',
pp:15,
description:"Ignores opponent's evasion for 3 turns, add Ground immunity.",
},
'Teleport':{
type:'Psychic',
category:'Status',
pp:20,
description:'Allows user to switch out. In the wild, the battle ends.',
},
'Thief':{
type:'Dark',
category:'Physical',
pp:10,
power:40,
accuracy:100,
tm:'TM46',
description:"May steal opponent's held item.",
probability:40,
},
'Thrash':{
type:'Normal',
category:'Physical',
pp:10,
power:120,
accuracy:100,
description:'User attacks for 2-3 turns but then becomes confused.',
},
'Thunder':{
type:'Electric',
category:'Special',
pp:10,
power:120,
accuracy:70,
tm:'TM25',
description:'May cause paralysis.',
probability:30,
},
'Thunder Fang':{
type:'Electric',
category:'Physical',
pp:15,
power:65,
accuracy:95,
description:'May cause paralysis and flinching.',
probability:10,
},
'Thunder Wave':{
type:'Electric',
category:'Status',
pp:20,
accuracy:100,
tm:'TM73',
description:'Causes paralysis.',
probability:100,
},
'Thunderbolt':{
type:'Electric',
category:'Special',
pp:15,
power:95,
accuracy:100,
tm:'TM24',
description:'May cause paralysis.',
probability:10,
},
'Thunderpunch':{
type:'Electric',
category:'Physical',
pp:15,
power:75,
accuracy:100,
description:'May cause paralysis.',
probability:10,
},
'Thundershock':{
type:'Electric',
category:'Special',
pp:30,
power:40,
accuracy:100,
description:'May cause paralysis.',
probability:10,
},
'Tickle':{
type:'Normal',
category:'Status',
pp:20,
accuracy:100,
description:"Decreases the opponent's Attack and Defense by one stage each.",
},
'Torment':{
type:'Dark',
category:'Status',
pp:15,
accuracy:100,
tm:'TM41',
description:'Opponent cannot use the same move in a row.',
},
'Toxic':{
type:'Poison',
category:'Status',
pp:10,
accuracy:90,
tm:'TM06',
description:'Causes poison that increases damage each turn.',
},
'Toxic Spikes':{
type:'Poison',
category:'Status',
pp:20,
description:'Hurts opponents when they switch into battle.',
},
'Transform':{
type:'Normal',
category:'Status',
pp:10,
description:'User takes on the form and attacks of the opponent.',
},
'Tri Attack':{
type:'Normal',
category:'Special',
pp:10,
power:80,
accuracy:100,
description:'May cause paralysis, freezing, or a burn',
probability:20,
},
'Trick':{
type:'Psychic',
category:'Status',
pp:10,
accuracy:100,
description:'Swaps held items with the opponent.',
},
'Trick Room':{
type:'Psychic',
category:'Status',
pp:5,
tm:'TM92',
description:'Slower Pokemon move first in the turn for 5 turns.',
},
'Triple Kick':{
type:'Fighting',
category:'Physical',
pp:10,
power:10,
accuracy:90,
description:'Hits 3 times, growing in power each with each hit.',
},
'Trump Card':{
type:'Normal',
category:'Special',
pp:5,
accuracy:100,
description:'The lower the PP, the higher the power.',
},
'Twineedle':{
type:'Bug',
category:'Physical',
pp:20,
power:25,
accuracy:100,
description:'Hits twice. May cause poison.',
probability:20,
},
'Twister':{
type:'Dragon',
category:'Special',
pp:20,
power:40,
accuracy:100,
description:'May cause flinching. 2x damage against an opponent using Fly.',
probability:20,
},
'U-turn':{
type:'Bug',
category:'Physical',
pp:20,
power:70,
accuracy:100,
tm:'TM89',
description:'User switches out immediately after attacking.',
},
'Uproar':{
type:'Normal',
category:'Special',
pp:10,
power:90,
accuracy:100,
description:'User attacks for 3 turns and prevents sleep.',
},
'V-Create':{
type:'Fire',
category:'Physical',
pp:5,
power:180,
accuracy:95,
description:"Lowers the user's Defense, Special Defense and Speed.",
probability:100,
},
'Vacuum Wave':{
type:'Fighting',
category:'Special',
pp:30,
power:40,
accuracy:100,
description:'User goes first.',
},
'Venoshock':{
type:'Poison',
category:'Special',
pp:10,
power:65,
accuracy:100,
description:'Inflicts double damage if the target is poisoned.',
},
'Vicegrip':{
type:'Normal',
category:'Physical',
pp:30,
power:55,
accuracy:100,
},
'Vine Whip':{
type:'Grass',
category:'Physical',
pp:15,
power:35,
accuracy:100,
},
'Vital Throw':{
type:'Fighting',
category:'Physical',
pp:10,
power:70,
description:'User attacks last, but cannot miss.',
},
'Volt Switch':{
type:'Electric',
category:'Special',
pp:20,
power:70,
accuracy:100,
description:'User must switch out after attacking.',
},
'Volt Tackle':{
type:'Electric',
category:'Physical',
pp:15,
power:120,
accuracy:100,
description:'User receives recoil damage.',
},
'Wake-up Slap':{
type:'Fighting',
category:'Physical',
pp:10,
power:60,
accuracy:100,
description:'Power doubles if used on a sleeping opponent, but wakes it up.',
},
'Water Gun':{
type:'Water',
category:'Special',
pp:25,
power:40,
accuracy:100,
},
'Water Pledge':{
type:'Water',
category:'Special',
pp:10,
power:50,
accuracy:100,
description:'Added effects appear if preceded by Fire Pledge or succeeded by Grass Pledge.',
},
'Water Pulse':{
type:'Water',
category:'Special',
pp:20,
power:60,
accuracy:100,
tm:'TM03',
description:'May cause confusion.',
probability:20,
},
'Water Sport':{
type:'Water',
category:'Status',
pp:15,
description:"Increases the user's Fire resistance.",
},
'Water Spout':{
type:'Water',
category:'Special',
pp:5,
power:150,
accuracy:100,
description:"The higher the user's HP, the higher the damage caused.",
},
'Waterfall':{
type:'Water',
category:'Physical',
pp:15,
power:80,
accuracy:100,
tm:'HM07',
description:'May cause flinching.',
probability:20,
},
'Weather Ball':{
type:'Normal',
category:'Special',
pp:10,
power:50,
accuracy:100,
description:"Move's power and type changes with the weather.",
},
'Whirlpool':{
type:'Water',
category:'Special',
pp:15,
power:35,
accuracy:85,
tm:'HM05',
description:'Damages opponent for 2-5 turns, opponent cannot switch/escape.',
},
'Whirlwind':{
type:'Normal',
category:'Status',
pp:20,
accuracy:100,
description:'In battles, the opponent switches. In the wild, the Pokemon runs.',
},
'Wide Guard':{
type:'Rock',
category:'Status',
pp:10,
description:"Protects the user's team from multi-target attacks.",
},
'Wild Charge':{
type:'Electric',
category:'Physical',
pp:15,
power:90,
accuracy:100,
description:'User receives 1/4 the damage it inflicts in recoil.',
},
'Will-o-wisp':{
type:'Fire',
category:'Status',
pp:15,
accuracy:75,
tm:'TM61',
description:'Causes a burn, if it hits.',
probability:100,
},
'Wing Attack':{
type:'Flying',
category:'Physical',
pp:35,
power:60,
accuracy:100,
},
'Wish':{
type:'Normal',
category:'Status',
pp:10,
description:'The user recovers HP in the following turn.',
},
'Withdraw':{
type:'Water',
category:'Status',
pp:40,
description:"Increases the user's Defense by one stage.",
},
'Wonder Room':{
type:'Psychic',
category:'Status',
pp:10,
description:"Swaps every Pokemon's Defense and Special Defense for 5 turns.",
},
'Wood Hammer':{
type:'Grass',
category:'Physical',
pp:15,
power:120,
accuracy:100,
description:'User receives recoil damage.',
},
'Work Up':{
type:'Normal',
category:'Status',
pp:30,
description:"Raises the user's Attack and Special Attack.",
},
'Worry Seed':{
type:'Grass',
category:'Status',
pp:10,
accuracy:100,
description:"Changes the opponent's Ability to Insomnia.",
},
'Wrap':{
type:'Normal',
category:'Physical',
pp:20,
power:15,
accuracy:90,
description:'Damages opponent for 2-5 turns, opponent cannot escape/switch.',
},
'Wring Out':{
type:'Normal',
category:'Special',
pp:5,
power:120,
accuracy:100,
description:"The higher the opponent's HP, the higher the damage.",
},
'X-Scissor':{
type:'Bug',
category:'Physical',
pp:15,
power:80,
accuracy:100,
tm:'TM81',
},
'Yawn':{
type:'Normal',
category:'Status',
pp:10,
description:'Puts the opponent to sleep in the following turn.',
},
'Zap Cannon':{
type:'Electric',
category:'Special',
pp:5,
power:120,
accuracy:50,
description:'Guaranteed to paralyze target, if it hits.',
probability:100,
},
}
